### ISSUE TITLE
GFG POTD Solution 

### ISSUE THREAD

**Issue by KaranShah1911** [Ayu-hack/GeeksforGeeks-POTD-Solution#163]
Have solved <strong>GFG POTD</strong>
**July**
26 - K-Pangrams
27 - Form a palindrome
29 - Row with max 1s
30 - Rat in a Maze Problem - I
31 - Longest Common Prefix of Strings

**August**
2 - Edit Distance
3 - The Celebrity Problem
7 - K-th element of two Arrays

@Ayu-hack, please assign this to me. I have the solutions

**Comment by Ayu-hack** [comment]
you DONT TO OPEN ISSUE. YOU NEED TO COMMENT IN ALREADY OPENED ISSUE OF RESPECTIVE MONTH like July and August.
