### ISSUE TITLE
Deletion and Reverse in Circular Linked List Solution

### ISSUE THREAD

**Issue by Ayu-hack** [Ayu-hack/GeeksforGeeks-POTD-Solution#2]
I want to add Deletion and Reverse in Circular Linked List Solution.

**Comment by GaurangMapuskar** [comment]
@Ayu-hack ,Please assign this issue to mee

**Comment by Ayu-hack** [comment]
@GaurangMapuskar please bring some new issue n unique.

More repos are available for pull requests, and they’re part of Hacktoberfest 2024.
Feel free to **tag me in your Hacktoberfest certificate or badges LinkedIn post**! 😄
👉 **Follow my GitHub and connect with me on** [LinkedIn](https://www.linkedin.com/in/ayush-tiwari02)!
⭐ **Star these repos** to stay updated for next year’s Hacktoberfest!
