### ISSUE TITLE
Adding algorithms

### ISSUE THREAD

**Issue by meghanakn473** [Ayu-hack/GeeksforGeeks-POTD-Solution#21]
Moore's Voting algorithm(Majority element of array), Kadane's Algorithm(Maximum Subarray), Dutch National Flag Algorithm(sorting array of 0's and 1's)

@Ayu-hack please assign me this issue under level 3 , gssoc-extd, hacktoberfest

**Comment by Ayu-hack** [comment]
Pick any issue and make PR under it and I will merge it.
