### ISSUE TITLE
Health Tool: GUI & Working BMI Calculator

### ISSUE THREAD

**Issue by labishbardiya** [Ayu-hack/GeeksforGeeks-POTD-Solution#24]
@Ayu-hack, I want to contribute a **BMI Calculator** as a mini-project for **Hacktoberfest 2024**. The calculator will allow users to input their **weight** (in kilograms) and **height** (in meters), and it will calculate their **Body Mass Index (BMI)** along with an indication of their **BMI category** (e.g., underweight, normal, overweight, obese).

### Key Features:

- Input for weight in kilograms.
- Input for height in meters.
- BMI calculation logic based on the formula: BMI = weight (kg) / [height (m)^2].
- Output displays the BMI value along with the corresponding BMI category.
- Error handling for invalid inputs (e.g., negative values, missing inputs).
- Display a health-related message or recommendations based on the BMI result.

### Technical Details:

- Language: Python.
- GUI using libraries like Tkinter (for Python).

### Results:

- The project will be a standalone utility with a simple, user-friendly interface.
- Submit a README file with instructions for running the BMI calculator and an explanation of its functionality.
- I will ensure code quality by following best practices, with clean and readable code.

I believe this feature would enhance the project by providing a useful and practical health-related tool. Looking forward to your feedback and suggestions before I start working on the feature!

**Comment by labishbardiya** [comment]
@Ayu-hack, To ensure smooth tracking and proper categorization of the issue, I would kindly request you to add the following labels if possible: `good first issue`, `hacktoberfest`, `documentation`.

**Comment by Ayu-hack** [comment]
there issues open already. work on it. provide solutions of previous potd
