### ISSUE TITLE
Adding a file in October - Build Tree in cpp 

### ISSUE THREAD

**Issue by AvinashUmrao** [Ayu-hack/GeeksforGeeks-POTD-Solution#302]

**Comment by AvinashUmrao** [comment]
@Ayu-hack 
Sir , kindly add labels of hactoberfest .
I have added a build tree program in October Folder.
It is proper Working code.

**Comment by AvinashUmrao** [comment]
@Ayu-hack I have created a PR

**Comment by Ayu-hack** [comment]
you need not to open new issue. there already opened issues , work on them. REF README CAREFULLY BEFORE CREATING PR.
