### ISSUE TITLE
 Solution Request for Linked List Matrix (POTD 9th October 2024)

### ISSUE THREAD

**Issue by pratikj697** [Ayu-hack/GeeksforGeeks-POTD-Solution#62]
Problem Statement:
The task is to convert a 2D matrix into a linked list matrix where each node in the matrix has two pointers:
1. One pointing to the next node in the same row (right pointer).
2. One pointing to the next node in the same column (down pointer).
3. The goal is to construct such a linked list matrix based on the input 2D array and provide a utility function to display the linked structure.

Can you assign this task to me under HacktoberFest 2024.

**Comment by Ayu-hack** [comment]
YOU DONT CREATE NEW ISSUE. ISSUES ARE ALREADY CREATED JUST COMMENT IN THAT , GET IT ASSIGNED AND WORK ON IT.
