### ISSUE TITLE
Leet Code Suggestion.

### ISSUE THREAD

**Issue by YogeshBabyOP** [Ayu-hack/GeeksforGeeks-POTD-Solution#63]
Can we Add LeetCode daily challenges, It was a good practice to solve leetcode daily challenges to improve DSA Skills 😄

![image](https://github.com/user-attachments/assets/7b7b5806-d8a2-4317-812a-189c545e3f9d)

**Comment by YogeshBabyOP** [comment]
It just a suggestion, as leetcode is highly preferable for FAANG Company interviews

**Comment by Ayu-hack** [comment]
YOU DONT OPEN ISSUE. I WILL OPEN THE ISSUE THEN YOU CAN ADD IN THAT FOLDER.
Thank you for understanding.

**Comment by Ayu-hack** [comment]
Brother @YogeshBabyOP I would suggest you to add solutions for February or July month. It will be easy for me to merge it.
