### ISSUE TITLE
Add POTD To April.

### ISSUE THREAD

**Issue by Mayur-nimkande-20** [Ayu-hack/GeeksforGeeks-POTD-Solution#81]
Hey @Ayu-hack i wanted to add POTD to "APRIL" month. Please assign me this task under #hacktoberfest2024.

**Comment by Ayu-hack** [comment]
DONT NEED TO OPEN ISSUE. APRIL MONTH SOLUTION ISSUE IS ALREADY OPENED. JUST COMMENT THERE ASSIGN ME . REF #15
