### ISSUE TITLE
i want to add project that is QR code Generator

### ISSUE THREAD

**Issue by tusharmishra069** [Ayu-hack/GeeksforGeeks-POTD-Solution#85]
![WhatsApp Image 2024-10-10 at 14 25 46](https://github.com/user-attachments/assets/6d38d378-a5b0-45bf-b43e-f5a3931db4cd)

firstly i raise this issue in other repo of yours, then after that u recommend me this, so here i am raising a issue.

I make this qr code generator using python lib. 

kindly assign me this, i feel lucky to do this.

**Comment by tusharmishra069** [comment]
.take

**Comment by Ayu-hack** [comment]
DONT NEED TO OPEN ISSUE. APRIL MONTH SOLUTION ISSUE IS ALREADY OPENED. JUST COMMENT THERE ASSIGN ME . REF #26

**Comment by tusharmishra069** [comment]
hey @Ayu-hack  can u assign me , i raise the isssue there

**Comment by Ayu-hack** [comment]
@tusharmishra069 assigned brother
